DEVELOPMENT_MODE: "development"

WEB_PORT: "0.0.0.0:10007"

PRODUCTION_CORS: "*"

KVSTORE_TYPE: "redis" # postgres, redis, inmemory map/mock
DEFAULT_TTL: 0

REDIS_ADDR: "localhost:6379"
REDIS_PWD: "1qazxsw23edcxz"
REDIS_DB_NUM: 0

DBSTORE_TYPE: "postgres" # postgres, sqlite, inmemory sqlite, pure mock
DB_DSN: "postgres://umf_user:umf_pwd@localhost:5432/umf?sslmode=disable"
DB_FILE: "umf_sqlite.db"
APPLY_MIGRATIONS: true
DB_DEBUG_LOG: false

DEFAULT_RECORDS_AMOUNT_TO_GET: 5
HASH_LENGTH: 8

